# Generated by Django 6.0.6 on 2026-06-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesor', models.IntegerField(unique=True)),
                ('nombre_asesor', models.CharField(max_length=150)),
                ('id_usuario', models.IntegerField()),
                ('maestra', models.IntegerField(default=0)),
                ('maestra_rebanadoras', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AsesorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesor', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('obj_volumen', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField(unique=True)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('obj_activacion', models.IntegerField(default=0)),
                ('tipo_obj_activacion', models.CharField(default='Porcentaje', max_length=50)),
                ('obj_volumen', models.IntegerField(default=0)),
                ('obj_profundidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('supervisor', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanamiento', models.CharField(blank=True, max_length=10, null=True)),
                ('asesor', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zona', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('clientes_actuales', models.IntegerField(default=0)),
                ('clientes_captar', models.IntegerField(default=0)),
                ('objetivo_principal', models.TextField(blank=True, default='', null=True)),
                ('categorias', models.TextField(blank=True, default='', null=True)),
                ('enfoque', models.TextField(blank=True, default='', null=True)),
                ('auditoria_jamones', models.IntegerField(default=0)),
                ('auditoria_quesos', models.IntegerField(default=0)),
                ('monto_proyectado_cobro', models.FloatField(default=0.0)),
                ('cajas_objetivo', models.FloatField(default=0.0)),
                ('kilos_objetivo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_region', models.IntegerField(unique=True)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosTarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField()),
                ('supervisor', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('total_clientes_dia', models.IntegerField(default=0)),
                ('clts_a_captar', models.IntegerField(default=0)),
                ('meta_cajas_matutina', models.FloatField(default=0.0)),
                ('meta_kilos_matutina', models.FloatField(default=0.0)),
                ('meta_cobranza_matutina', models.FloatField(default=0.0)),
                ('cajas_reales', models.FloatField(default=0.0)),
                ('kilos_reales', models.FloatField(default=0.0)),
                ('monto_cobrado_real', models.FloatField(default=0.0)),
                ('clientes_activados', models.IntegerField(default=0)),
                ('clientes_apertura_nuevos', models.IntegerField(default=0)),
                ('clts_visita_con_pop', models.IntegerField(default=0)),
                ('clts_con_1_sku', models.IntegerField(default=0)),
                ('clts_con_2_sku', models.IntegerField(default=0)),
                ('clts_con_mas_3_sku', models.IntegerField(default=0)),
                ('cumplio_pasos_visita', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('usa_catalogo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('calidad_atencion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('audito_jamon', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('obs_jamon_concurso', models.TextField(blank=True, default='', null=True)),
                ('audito_queso', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('obs_queso_concurso', models.TextField(blank=True, default='', null=True)),
                ('cumplimiento_plan', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('novedades_market', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField(unique=True)),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sucursal', models.IntegerField(unique=True)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('id_region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('id_rol', models.IntegerField()),
                ('id_region', models.IntegerField()),
                ('id_sucursal', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
