# Generated by Django 6.0.6 on 2026-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesor', models.CharField(max_length=100)),
                ('id_categoria', models.IntegerField()),
                ('act_lleva', models.FloatField(default=0.0)),
                ('vol_lleva', models.FloatField(default=0.0)),
                ('prof_lleva', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='asesor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.AlterField(
            model_name='asesor',
            name='id_asesor',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='id_usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='maestra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asesor',
            name='maestra_rebanadoras',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asesorcategoria',
            name='id_asesor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asesorcategoria',
            name='obj_volumen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
