# Generated by Django 6.0.6 on 2026-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_seguimientodiario_remove_asesor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='id_region',
            field=models.IntegerField(default=0),
        ),
    ]
