# Generated by Django 6.0.6 on 2026-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_categoria_id_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mes',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
