# Generated by Django 6.0.6 on 2026-06-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_categoria_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_asesor', models.CharField(max_length=100)),
                ('id_categoria', models.IntegerField()),
                ('act_dia', models.FloatField(default=0.0)),
                ('vol_dia', models.FloatField(default=0.0)),
                ('prof_dia', models.FloatField(default=0.0)),
            ],
        ),
    ]
