# Generated by Django 6.0.6 on 2026-06-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_registrodiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionsemanal',
            name='categorias',
        ),
    ]
