# Generated by Django 6.0.6 on 2026-06-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_planificacionsemanal_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='obj_profundidad',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_medida',
            field=models.CharField(choices=[('caja', 'Caja'), ('kilo', 'Kilo'), ('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
    ]
