# Generated by Django 6.0.6 on 2026-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_remove_categoria_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorcategoria',
            name='obj_profundidad',
            field=models.FloatField(default=0.0),
        ),
    ]
