# Generated by Django 6.0.6 on 2026-06-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_asesorcategoria_obj_profundidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorcategoria',
            name='obj_profundidad',
        ),
    ]
