# Generated by Django 6.0.6 on 2026-06-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_merge_0008_0010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacionsemanal',
            unique_together={('fecha', 'supervisor')},
        ),
    ]
