# Generated by Django 6.0.6 on 2026-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_alter_planificacionsemanal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='mes',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
